### ISSUE TITLE
x86_64 android build

### ISSUE THREAD

**Issue by sigmaSd** [fm-elpac/v8-src#1]
@secext2022 hello thanks for this project

 It would be great if you add x86_64 android build, I imagine its not that hard, since you already have aarch64

The motivation is I'm using termux on [waydroid](https://github.com/waydroid/waydroid),  and it would be great if I can run deno on it

**Comment by secext2022** [comment]
ok, I will try to add `x86_64` android after deno 1.36.0 release.
But I do not have a x86_64 android device so can not test.

Now you can try directly build deno for x86_64 android (with official source code).
Because the CPU is the same (x86_64), so the snapshot should just work.

Most part of this project is to solve the snapshot problem, which occur when the host CPU (x86_64) and target CPU (aarch64) is different.

**Comment by sigmaSd** [comment]
Just to expend more, to have x86_64 android I can use waydroid or genymotion locally, 

To build x86_64 android I need to build deno inside either . But my pc is old so I usually use services like gitpod to build on the cloud, but there I don't have waydroid or genymotion so my only option is to cross compile but this won't work because of snapshotting.

Btw the needed patch seems not that big for x86_64 android https://github.com/denoland/deno/compare/main...sigmaSd:deno:and?expand=1 maybe this should be added to upstream

Anyway thanks for your help, I'm still exploring different way to do this, if I manege to make it work I'll mention how and close this issue

**Comment by sigmaSd** [comment]
I also tried proot (I thought its the easiest way) but that errors https://github.com/proot-me/proot/issues/363

**Comment by sigmaSd** [comment]
I started testing  termux-docker as well, still WIP since I'm not familiar with this https://github.com/sigmaSd/t8664/blob/master/.github/workflows/build.yml

**Comment by secext2022** [comment]
Sorry, I can not build deno for `x86_64-linux-android`,
because `rusqlite` can not build for x86_64 android.

<https://github.com/rusqlite/rusqlite/issues/1380>

**Comment by sigmaSd** [comment]
@secext2022 thanks a lot for taking the time to test this

I figured how to make deno work with proot by patching mio (proot seems to not handle epoll_wait) so this issue is not very important now (obviously no proot is better but it's not a deal breaker)

**Comment by secext2022** [comment]
Build deno for `x86_64-linux-android` is here (<https://github.com/fm-elpac/v8-src/tree/deno-1.36-x64>).

Please test.
Download binary from <https://github.com/fm-elpac/v8-src/actions/runs/5950884443>

**Comment by sigmaSd** [comment]
Awesome works indeed!
Thanks again

side note maybe you should consider renaming the repo to something more discoverable like deno-android-builds or something

**Comment by secext2022** [comment]
I did not rename the repo, but I update Description and Topics, so search `deno android` on github should work.

**Comment by secext2022** [comment]
@sigmaSd   

Maybe you are interested in this issue: <https://github.com/termux/termux-packages/issues/17398>
